//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchParams) DeepCopyInto(out *ArchParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchParams.
func (in *ArchParams) DeepCopy() *ArchParams {
	if in == nil {
		return nil
	}
	out := new(ArchParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Behavior) DeepCopyInto(out *Behavior) {
	*out = *in
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScalingBehavior)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(ScalingBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Behavior.
func (in *Behavior) DeepCopy() *Behavior {
	if in == nil {
		return nil
	}
	out := new(Behavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPerCountConstraint) DeepCopyInto(out *CapacityPerCountConstraint) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPerCountConstraint.
func (in *CapacityPerCountConstraint) DeepCopy() *CapacityPerCountConstraint {
	if in == nil {
		return nil
	}
	out := new(CapacityPerCountConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Constraints) DeepCopyInto(out *Constraints) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MinCountPerReplica != nil {
		in, out := &in.MinCountPerReplica, &out.MinCountPerReplica
		*out = new(int32)
		**out = **in
	}
	if in.MaxCountPerReplica != nil {
		in, out := &in.MaxCountPerReplica, &out.MaxCountPerReplica
		*out = new(int32)
		**out = **in
	}
	if in.CapacityPerCount != nil {
		in, out := &in.CapacityPerCount, &out.CapacityPerCount
		*out = make(map[corev1.ResourceName]CapacityPerCountConstraint, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Constraints.
func (in *Constraints) DeepCopy() *Constraints {
	if in == nil {
		return nil
	}
	out := new(Constraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomQueries) DeepCopyInto(out *CustomQueries) {
	*out = *in
	if in.DeviceResourceMetrics != nil {
		in, out := &in.DeviceResourceMetrics, &out.DeviceResourceMetrics
		*out = make(map[string]DeviceResourceMetrics, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomQueries.
func (in *CustomQueries) DeepCopy() *CustomQueries {
	if in == nil {
		return nil
	}
	out := new(CustomQueries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceResourceMetrics) DeepCopyInto(out *DeviceResourceMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceResourceMetrics.
func (in *DeviceResourceMetrics) DeepCopy() *DeviceResourceMetrics {
	if in == nil {
		return nil
	}
	out := new(DeviceResourceMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryResults) DeepCopyInto(out *DiscoveryResults) {
	*out = *in
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(v1.OwnerReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryResults.
func (in *DiscoveryResults) DeepCopy() *DiscoveryResults {
	if in == nil {
		return nil
	}
	out := new(DiscoveryResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hint) DeepCopyInto(out *Hint) {
	*out = *in
	if in.ModelParams != nil {
		in, out := &in.ModelParams, &out.ModelParams
		*out = new(ArchParams)
		**out = **in
	}
	if in.MaxNumBatchedTokens != nil {
		in, out := &in.MaxNumBatchedTokens, &out.MaxNumBatchedTokens
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hint.
func (in *Hint) DeepCopy() *Hint {
	if in == nil {
		return nil
	}
	out := new(Hint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencyEstimation) DeepCopyInto(out *LatencyEstimation) {
	*out = *in
	if in.TimeToFirstTokenMilliseconds != nil {
		in, out := &in.TimeToFirstTokenMilliseconds, &out.TimeToFirstTokenMilliseconds
		*out = new(int32)
		**out = **in
	}
	if in.InterTokenLatencyMilliseconds != nil {
		in, out := &in.InterTokenLatencyMilliseconds, &out.InterTokenLatencyMilliseconds
		*out = new(int32)
		**out = **in
	}
	if in.TimeToFirstTokenOffsetMilliseconds != nil {
		in, out := &in.TimeToFirstTokenOffsetMilliseconds, &out.TimeToFirstTokenOffsetMilliseconds
		*out = new(int32)
		**out = **in
	}
	if in.InterTokenLatencyOffsetMilliseconds != nil {
		in, out := &in.InterTokenLatencyOffsetMilliseconds, &out.InterTokenLatencyOffsetMilliseconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencyEstimation.
func (in *LatencyEstimation) DeepCopy() *LatencyEstimation {
	if in == nil {
		return nil
	}
	out := new(LatencyEstimation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricHealth) DeepCopyInto(out *MetricHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricHealth.
func (in *MetricHealth) DeepCopy() *MetricHealth {
	if in == nil {
		return nil
	}
	out := new(MetricHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	if in.CustomQueries != nil {
		in, out := &in.CustomQueries, &out.CustomQueries
		*out = new(CustomQueries)
		(*in).DeepCopyInto(*out)
	}
	if in.RateRangeSeconds != nil {
		in, out := &in.RateRangeSeconds, &out.RateRangeSeconds
		*out = new(int32)
		**out = **in
	}
	if in.LatencyPercentile != nil {
		in, out := &in.LatencyPercentile, &out.LatencyPercentile
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStatus) DeepCopyInto(out *MonitoringStatus) {
	*out = *in
	if in.MetricHealths != nil {
		in, out := &in.MetricHealths, &out.MetricHealths
		*out = make([]MetricHealth, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStatus.
func (in *MonitoringStatus) DeepCopy() *MonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCAControllerConfig) DeepCopyInto(out *RCAControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCAControllerConfig.
func (in *RCAControllerConfig) DeepCopy() *RCAControllerConfig {
	if in == nil {
		return nil
	}
	out := new(RCAControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCAControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCAControllerConfigList) DeepCopyInto(out *RCAControllerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RCAControllerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCAControllerConfigList.
func (in *RCAControllerConfigList) DeepCopy() *RCAControllerConfigList {
	if in == nil {
		return nil
	}
	out := new(RCAControllerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RCAControllerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCAControllerConfigSpec) DeepCopyInto(out *RCAControllerConfigSpec) {
	*out = *in
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(Logging)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCAControllerConfigSpec.
func (in *RCAControllerConfigSpec) DeepCopy() *RCAControllerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RCAControllerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCAControllerConfigStatus) DeepCopyInto(out *RCAControllerConfigStatus) {
	*out = *in
	if in.MonitoringStatus != nil {
		in, out := &in.MonitoringStatus, &out.MonitoringStatus
		*out = new(MonitoringStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCAControllerConfigStatus.
func (in *RCAControllerConfigStatus) DeepCopy() *RCAControllerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RCAControllerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimAutoscaler) DeepCopyInto(out *ResourceClaimAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimAutoscaler.
func (in *ResourceClaimAutoscaler) DeepCopy() *ResourceClaimAutoscaler {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceClaimAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimAutoscalerList) DeepCopyInto(out *ResourceClaimAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceClaimAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimAutoscalerList.
func (in *ResourceClaimAutoscalerList) DeepCopy() *ResourceClaimAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceClaimAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimAutoscalerSpec) DeepCopyInto(out *ResourceClaimAutoscalerSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.TargetLatency != nil {
		in, out := &in.TargetLatency, &out.TargetLatency
		*out = new(TargetLatency)
		(*in).DeepCopyInto(*out)
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(Constraints)
		(*in).DeepCopyInto(*out)
	}
	if in.MinTargetUtilization != nil {
		in, out := &in.MinTargetUtilization, &out.MinTargetUtilization
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimAutoscalerSpec.
func (in *ResourceClaimAutoscalerSpec) DeepCopy() *ResourceClaimAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimAutoscalerStatus) DeepCopyInto(out *ResourceClaimAutoscalerStatus) {
	*out = *in
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(DiscoveryResults)
		(*in).DeepCopyInto(*out)
	}
	if in.ScalingResults != nil {
		in, out := &in.ScalingResults, &out.ScalingResults
		*out = new(ScalingResults)
		(*in).DeepCopyInto(*out)
	}
	if in.ScalingStatus != nil {
		in, out := &in.ScalingStatus, &out.ScalingStatus
		*out = new(ScalingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimAutoscalerStatus.
func (in *ResourceClaimAutoscalerStatus) DeepCopy() *ResourceClaimAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBehavior) DeepCopyInto(out *ScalingBehavior) {
	*out = *in
	out.Trigger = in.Trigger
	if in.SingleTimeScalingLimit != nil {
		in, out := &in.SingleTimeScalingLimit, &out.SingleTimeScalingLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBehavior.
func (in *ScalingBehavior) DeepCopy() *ScalingBehavior {
	if in == nil {
		return nil
	}
	out := new(ScalingBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingResults) DeepCopyInto(out *ScalingResults) {
	*out = *in
	if in.LastEstimationTime != nil {
		in, out := &in.LastEstimationTime, &out.LastEstimationTime
		*out = (*in).DeepCopy()
	}
	if in.LastEstimation != nil {
		in, out := &in.LastEstimation, &out.LastEstimation
		*out = new(LatencyEstimation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingResults.
func (in *ScalingResults) DeepCopy() *ScalingResults {
	if in == nil {
		return nil
	}
	out := new(ScalingResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingStatus) DeepCopyInto(out *ScalingStatus) {
	*out = *in
	if in.LastApplyTime != nil {
		in, out := &in.LastApplyTime, &out.LastApplyTime
		*out = (*in).DeepCopy()
	}
	if in.DesiredReplicas != nil {
		in, out := &in.DesiredReplicas, &out.DesiredReplicas
		*out = new(int32)
		**out = **in
	}
	if in.ReadyReplicas != nil {
		in, out := &in.ReadyReplicas, &out.ReadyReplicas
		*out = new(int32)
		**out = **in
	}
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingStatus.
func (in *ScalingStatus) DeepCopy() *ScalingStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingTrigger) DeepCopyInto(out *ScalingTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingTrigger.
func (in *ScalingTrigger) DeepCopy() *ScalingTrigger {
	if in == nil {
		return nil
	}
	out := new(ScalingTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetLatency) DeepCopyInto(out *TargetLatency) {
	*out = *in
	if in.EndToEndLatencyMilliseconds != nil {
		in, out := &in.EndToEndLatencyMilliseconds, &out.EndToEndLatencyMilliseconds
		*out = new(int32)
		**out = **in
	}
	if in.TimeToFirstTokenLatencyMilliseconds != nil {
		in, out := &in.TimeToFirstTokenLatencyMilliseconds, &out.TimeToFirstTokenLatencyMilliseconds
		*out = new(int32)
		**out = **in
	}
	if in.InterTokenLatencyMilliseconds != nil {
		in, out := &in.InterTokenLatencyMilliseconds, &out.InterTokenLatencyMilliseconds
		*out = new(int32)
		**out = **in
	}
	if in.ToleranceMilliseconds != nil {
		in, out := &in.ToleranceMilliseconds, &out.ToleranceMilliseconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetLatency.
func (in *TargetLatency) DeepCopy() *TargetLatency {
	if in == nil {
		return nil
	}
	out := new(TargetLatency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSelector) DeepCopyInto(out *TargetSelector) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	out.ResourceRef = in.ResourceRef
	if in.Hint != nil {
		in, out := &in.Hint, &out.Hint
		*out = new(Hint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSelector.
func (in *TargetSelector) DeepCopy() *TargetSelector {
	if in == nil {
		return nil
	}
	out := new(TargetSelector)
	in.DeepCopyInto(out)
	return out
}
